# generated by datamodel-codegen:
#   filename:  contracts.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class EntityId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="An opaque stable Agent Hub identifier. Clients must not parse it.",
            max_length=128,
            min_length=1,
        ),
    ]


class ErrorEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[str, Field(min_length=1)]
    message: Annotated[str, Field(min_length=1)]
    request_id: Annotated[EntityId, Field(alias="requestId")]
    retryable: bool
    details: dict[str, Any] | None = None


class ArtifactSchemaBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(min_length=1)]
    version: Annotated[str, Field(min_length=1)]


class ArtifactPluginBinding(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(min_length=1)]
    version: Annotated[str, Field(min_length=1)]


class ArtifactProvenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    created_by_thread_id: Annotated[EntityId, Field(alias="createdByThreadId")]
    created_by_run_id: Annotated[EntityId, Field(alias="createdByRunId")]
    last_changed_by_thread_id: Annotated[EntityId, Field(alias="lastChangedByThreadId")]
    last_changed_by_run_id: Annotated[EntityId, Field(alias="lastChangedByRunId")]


class ArtifactRelation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Annotated[str, Field(min_length=1)]
    target_artifact_id: Annotated[EntityId, Field(alias="targetArtifactId")]


class ArtifactEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: EntityId
    type: Annotated[str, Field(min_length=1)]
    document_version: Annotated[int, Field(alias="documentVersion", ge=1)]
    title: Annotated[str, Field(max_length=240, min_length=1)]
    summary: Annotated[str | None, Field(max_length=2000)] = None
    schema_: Annotated[ArtifactSchemaBinding, Field(alias="schema")]
    plugin: ArtifactPluginBinding
    provenance: ArtifactProvenance
    relations: list[ArtifactRelation]


class ArtifactDocument(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact: ArtifactEnvelope
    payload: dict[str, Any]


class AgentRunStatus(StrEnum):
    queued = "queued"
    running = "running"
    interrupted = "interrupted"
    cancelling = "cancelling"
    cancelled = "cancelled"
    succeeded = "succeeded"
    failed = "failed"


class AgentRun(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: EntityId
    thread_id: Annotated[EntityId, Field(alias="threadId")]
    status: AgentRunStatus
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]
    error: ErrorEnvelope | None = None


class ProjectFilePreview(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[str, Field(max_length=1032, min_length=1)]
    content: str
    version: Annotated[int, Field(ge=1)]


class ScratchFilePreview(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: Annotated[str, Field(max_length=1032, min_length=1)]
    content: str


class Project(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: EntityId
    name: Annotated[str, Field(max_length=120, min_length=1)]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]


class Thread(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: EntityId
    project_id: Annotated[EntityId, Field(alias="projectId")]
    title: Annotated[str, Field(max_length=160, min_length=1)]
    created_at: Annotated[AwareDatetime, Field(alias="createdAt")]
    updated_at: Annotated[AwareDatetime, Field(alias="updatedAt")]


class FoundationContracts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    agent_run: Annotated[AgentRun | None, Field(alias="agentRun")] = None
    artifact_document: Annotated[ArtifactDocument | None, Field(alias="artifactDocument")] = None
    error: ErrorEnvelope | None = None
    project_file_preview: Annotated[
        ProjectFilePreview | None, Field(alias="projectFilePreview")
    ] = None
    scratch_file_preview: Annotated[
        ScratchFilePreview | None, Field(alias="scratchFilePreview")
    ] = None
    project: Project | None = None
    thread: Thread | None = None
